Create database cunsumer;
use cunsumer;
select * from customer_shopping_behavior;

-- creat another table for analysis
create table csb
like customer_shopping_behavior;

-- --insert into csb
 insert into csb
 (select* from customer_shopping_behavior);
 
-- check csb
select* from csb;

-- changing column name
ALTER TABLE csb 
RENAME COLUMN `ï»¿Customer ID` TO `Customer`;

ALTER TABLE csb 
RENAME COLUMN `Customer` TO `Customer_id`;

-- To check for duplicates
WITH cte AS (
    SELECT *,
           ROW_NUMBER() OVER(PARTITION BY Customer_id ORDER BY Customer_id) AS row_num
    FROM csb
)
SELECT * FROM cte 
WHERE row_num > 1;
-- THERe are no dublicates

-- finding null values
SELECT * FROM csb
WHERE Customer_id IS NULL
   OR Age IS NULL
   OR Gender IS NULL
   OR `Item Purchased` IS NULL
   OR Category IS NULL
   OR `Purchase Amount (USD)` IS NULL
   OR Location IS NULL
   OR Size IS NULL
   OR Color IS NULL
   OR Season IS NULL
   OR `Review Rating` IS NULL
   OR `Subscription Status` IS NULL
   OR `Shipping Type` IS NULL
   OR `Discount Applied` IS NULL
   OR `Promo Code Used` IS NULL
   OR `Previous Purchases` IS NULL
   OR `Payment Method` IS NULL
   OR `Frequency of Purchases` IS NULL;
-- no null values

-- --check for null and blank spaces 
SELECT * FROM csb
WHERE 
   Customer_id IS NULL
   OR Age IS NULL
   OR `Purchase Amount (USD)` IS NULL
   OR `Review Rating` IS NULL
   OR `Previous Purchases` IS NULL
   OR Gender IS NULL OR TRIM(Gender) = ''
   OR `Item Purchased` IS NULL OR TRIM(`Item Purchased`) = ''
   OR Category IS NULL OR TRIM(Category) = ''
   OR Location IS NULL OR TRIM(Location) = ''
   OR Size IS NULL OR TRIM(Size) = ''
   OR Color IS NULL OR TRIM(Color) = ''
   OR Season IS NULL OR TRIM(Season) = ''
   OR `Subscription Status` IS NULL OR TRIM(`Subscription Status`) = ''
   OR `Shipping Type` IS NULL OR TRIM(`Shipping Type`) = ''
   OR `Discount Applied` IS NULL OR TRIM(`Discount Applied`) = ''
   OR `Promo Code Used` IS NULL OR TRIM(`Promo Code Used`) = ''
   OR `Payment Method` IS NULL OR TRIM(`Payment Method`) = ''
   OR `Frequency of Purchases` IS NULL OR TRIM(`Frequency of Purchases`) = '';
-- --no null n blank spaces 

-- creting a new column age_group
alter table csb
add column age_group varchar(100);

Update csb
set age_group =case
		when Age is null then 'unknown'
        when Age<30 then 'yound_adult'
        when Age between 30 and 44 then 'adult'
        when Age between 45 and 64 then 'middle_age'
        else 'seniour'
end;

select*from csb;

-- --adding frequency column
 select distinct `Frequency of Purchases` from csb;
 
 alter table csb
 add column frequency_num int;
 
 update csb
 set frequency_num = case
		when `Frequency of Purchases`='Fortnightly' then 14
		when `Frequency of Purchases`='Weekly'  then 7
		when `Frequency of Purchases`='Annually'  then 30 
		when `Frequency of Purchases`='Quarterly'  then 90
		when `Frequency of Purchases`='Bi-Weekly'  then 14
		when `Frequency of Purchases`='Monthly' then  365
		when `Frequency of Purchases`='Every 3 Months' then 90
		else 0
end;
 
alter table csb
drop column `Promo Code Used`;
 
 
 
 
 -- --Q1 revenur generated by male and female
select Gender,sum(`Purchase Amount (USD)`) as revenue
from csb
group by Gender;

--  --Q2 which customer uses discount but still spent more than avg purchase amount
select Customer_id ,
`Purchase Amount (USD)`  from csb
where `Discount Applied`='Yes' and `Purchase Amount (USD)`>(
select avg(`Purchase Amount (USD)`) as avg_purchase_amount 
from csb);
 
-- --Q3 top 5 product with highest avg review rating 
select `Item Purchased` ,Round(avg(`Review Rating`),2) as 'avg_product_rating'
from csb
group by `Item Purchased`
order by 'avg_product_rating'
limit 5;

-- --Q4 compare the avg purchase amount between standard and express shipping.
select `Shipping Type`, round(avg(`Purchase Amount (USD)`),2) as purchase
from csb
where `Shipping Type` in('Standard','Express')
group by `Shipping Type`;

-- Q5 do subscribers spend more ,compare avg spend and total revenue between subscribers and non sucescribers
select `Subscription Status`,
count(Customer_id) as total_customer,
round(avg(`Purchase Amount (USD)`),2) as avg_spend,
round(sum(`Purchase Amount (USD)`),2) as total_spend
from csb
group by  `Subscription Status`
order by  total_spend,avg_spend desc;

-- Q6 which 5 product have the highest percentage of purchase with discount applied
select `Item Purchased`,
round(100*sum(case 
	when `Discount Applied`='Yes' then 1
    else 0  end)/count(*),2) as discount_rate
from csb
group by  `Item Purchased`
order by  discount_rate desc
limit 5;


-- Q7 segment customers into  new ,returning ,and loyal based on their total
-- number of previous purchases and show the count of ech segment.

with customer_type as(
select Customer_id ,`Previous Purchases`,
case 
	when`Previous Purchases` =1 then 'New'
    when `Previous Purchases` between 2 and 10 then 'Returning'
    else 'Loyal'
end as customer_segment
from csb
)

select customer_segment, count(*) as number_of_customer
from customer_type
group by customer_segment;

-- Q8 what asr the top 3 most purchases products with in each category
 With item_count as(
select `Category`, `Item Purchased`,
count(`Customer_id`) as total_orders,
row_number() over(partition by `Category` order by count(`Customer_id`) desc) as item_rank
from csb
group by `Category`,`Item Purchased`
)
select item_rank,`Category`,`Item Purchased`, total_orders
from item_count 
where item_rank<=3;

-- Q9 are customer who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select `Subscription Status`,
count(Customer_id) as repeat_buyers
from csb
where `Previous Purchases`>5
group by `Subscription Status` ;


-- Q10 what is the revene contribution of each age group
select age_group,
sum(`Purchase Amount (USD)`) as total_revenue
from csb
group by age_group 
order by total_revenue desc;

select * from csb
limit 3863;

select* from csb;

